[aws]
symbol = "  "
disabled = false

[buf]
symbol = " "
disabled = false

[c]
symbol = " "
disabled = false

[cmake]
symbol = " "
disabled = false

[conda]
symbol = " "
disabled = false

[crystal]
symbol = " "
disabled = false

[dart]
symbol = " "
disabled = false

[directory]
read_only = " 󰌾"
disabled = false

[docker_context]
symbol = " "
disabled = false

[elixir]
symbol = " "
disabled = false

[elm]
symbol = " "
disabled = false

[fennel]
symbol = " "
disabled = false

[fossil_branch]
symbol = " "
disabled = false

[git_branch]
symbol = " "
disabled = false

[git_commit]
tag_symbol = '  '
disabled = false

[golang]
symbol = " "
disabled = false

[guix_shell]
symbol = " "
disabled = false

[haskell]
symbol = " "
disabled = false

[haxe]
symbol = " "
disabled = false

[hg_branch]
symbol = " "
disabled = false

[hostname]
ssh_symbol = " "
disabled = false

[java]
symbol = " "
disabled = false

[julia]
symbol = " "
disabled = false

[kotlin]
symbol = " "
disabled = false

[lua]
symbol = " "
disabled = false

[memory_usage]
symbol = "󰍛 "
disabled = false

[meson]
symbol = "󰔷 "
disabled = false

[nim]
symbol = "󰆥 "
disabled = false

[nix_shell]
symbol = " "
disabled = false

[nodejs]
symbol = " "
disabled = false

[ocaml]
symbol = " "
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = false

[perl]
symbol = " "
disabled = false

[php]
symbol = " "
disabled = false

[pijul_channel]
symbol = " "
disabled = false

[python]
symbol = " "
disabled = false

[rlang]
symbol = "󰟔 "
disabled = false

[ruby]
symbol = " "
disabled = false

[rust]
symbol = "󱘗 "
disabled = false

[scala]
symbol = " "
disabled = false

[swift]
symbol = " "
disabled = false

[zig]
symbol = " "
disabled = false

[gradle]
symbol = " "
disabled = false
